### ISSUE TITLE
Request: ARM release

### ISSUE THREAD

**Issue by xtc0r** [stake-house/wagyu-key-gen#160]
Thanks for the great tool and the time you put into this!

Could you provide an ARM release as well?

I tried to build it from source but got an error when executing `yarn install`
``` 
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /home/rock/Downloads/wagyu-key-gen/.yarn/releases/yarn-berry.cjs:426:2642
    at Object.<anonymous> (/home/rock/Downloads/wagyu-key-gen/.yarn/releases/yarn-berry.cjs:723:7786)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

**Comment by xtc0r** [comment]
I use ubuntu 20.02. Thanks for considering.
